tenants:
  clientA:
    active: true
    name: "Entreprise A"
    match:
      subdomain: "client-a"      # http://client-a:3000
      path: "client-a"           # http://localhost:3000/client-a
    paths:
      form: "./tenants/clientA/form.json"
      action: "./tenants/clientA/action.js"
    theme:
      primaryColor: "#4f46e5"
    metaKey: "codeProjet"
  clientB:
      active: true
      name: "Service Recrutement RH"
      match:
        subdomain: "client-b"
        path: "client-b"
      paths:
        form: "./tenants/clientB/form.json"
        action: "./tenants/clientB/action.js"
      theme:
        primaryColor: "#059669" # Vert
      metaKey: "nomCandidat"